export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_INPUTS = "ADD_INPUTS";
export const ADD_LOCATION = "ADD_LOCATION";
export const SAVE_CAMPAIGN = "SAVE_CAMPAIGN";
export const SAVE_LOGGED_IN_USER = "SAVE_LOGGED_IN_USER";