export const GET_LOCATION = "GET_LOCATION"; // from browser
export const ADD_CATEGORY = "ADD_CATEGORY";
export const ADD_NEW_CAMP = "ADD_NEW_CAMP";
export const ADD_LOCATION = "ADD_LOCATION";
export const GET_ALL_CAMP = "GET_ALL_CAMP";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const SAVE_CAMPAIGN = "SAVE_CAMPAIGN";
export const SAVE_LOGGED_IN_USER = "SAVE_LOGGED_IN_USER";
export const AUTH_SIGN_UP = "AUTH_SIGN_UP";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_SIGN_OUT = "AUTH_SIGN_OUT";
export const AUTH_SIGN_IN = "AUTH_SIGN_IN";
export const GET_CAMP_ID = "GET_CAMP_ID";
